#!/bin/bash

curl -s "https://aviationweather.gov/api/data/metar?ids=KMCI&format=json&taf=false&hours=12&bbox=40%2C-90%2C45%2C-85" > aviation.json

data=$(jq -r '.[].receiptTime' aviation.json)

echo "$data" | head -n 6
